
name: Quarto Publish

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install TeX dependencies
        run: |
          TEXLIVE_DIR="${HOME}/.TinyTeX"
          TEXLIVE_BIN="$TEXLIVE_DIR/bin/$(uname -m)-linux"
          export PATH="$TEXLIVE_BIN:$PATH"
          tlmgr install tex-gyre collection-fontsrecommended
          tlmgr path add
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr","rmarkdown"), repos="https://cloud.r-project.org")'
      - name: Render
        run: quarto render
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          create-branch: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
