
name: Quarto Publish

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'stable'
      - name: Install TinyTeX (for PDF)
        uses: r-lib/actions/setup-tinytex@v2
      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}