
name: Quarto Publish

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install TeX dependencies
        run: |
          TEXLIVE_ROOT=$(kpsewhich -var-value=SELFAUTOPARENT)
          TEXLIVE_BIN="$TEXLIVE_ROOT/bin/$(uname -m)-linux"
          "$TEXLIVE_BIN/tlmgr" install tex-gyre collection-fontsrecommended
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr","rmarkdown"), repos="https://cloud.r-project.org")'
      - name: Render
        run: quarto render
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
